version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-compose-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crs_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
